#! /bin/sh

xset s off
xset -dpms

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-0 -d I II III
bspc monitor HDMI-A-0 -d IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a steam state=floating desktop='^5'

bash .config/polybar/launch.sh &
nitrogen --restore &
picom &

